### ISSUE TITLE
Mixing text and variables hightlighting

### ISSUE THREAD

**Issue by rubenmoya** [ezekg/language-haml#53]
I've discovered that you can mix text and variables using Ruby/Haml interpolation like this:

```%p Lorem ipsum #{variable} dolor sit amet```

I think it would be nice if it were in other color and not white like it is right now:

<img width="402" alt="screen shot 2015-12-07 at 22 36 33" src="https://cloud.githubusercontent.com/assets/905225/11640494/02c3e84e-9d33-11e5-9688-ac37ecdeea9d.png">

Maybe I'm wrong and I shouldn't be doing that because it's not a good practice or something, so, what do you think guys?

**Comment by ezekg** [comment]
Well, that's going to vary depending on your Ruby syntax theme. Most syntax themes have white variables by default. If you want to change it, you can add something like this into your stylesheet config (**Atom**->**Open Your Stylesheet**):

```less
atom-text-editor,
atom-text-editor::shadow {

  // Adjust embedded Ruby variable colors
  .haml .meta.embedded.ruby {
    color: #f33 !important;
  }
}
```

That's perfectly valid Haml, btw. I use interpolation like that all of the time. :+1:
